### ISSUE TITLE
Cambios a clase Stats

### ISSUE THREAD

**Issue by CristianDavid** [CristianDavid/field-validator#2]
1. Poder guardar los resultados (media, moda, mediana, etc), en los columnInfo que recibe el constructor para que puedan ser utilizados por procesos posteriores.
2. Escribir en Stats.csv las frecuencias y errores también para atributos numéricos.

**Comment by oscarAdrianMariscal** [comment]
Ya se pasan los datos a column info a8bd57c523b24e310e315f1d54c841b9a796f55f

**Comment by CristianDavid** [comment]
@oscarAdrianMariscal 
Por cierto, usa las clases que heredan de ColumnInfo: NumericColumnInfo y NominalColumnInfo,
osea "var instanceof NumericColumnInfo" en lugar de var.isNumeric().

**Comment by oscarAdrianMariscal** [comment]
ya termine de implementar el requerimiento numero dos
86ab9367c01d20be220103960ca49fe0fb04b1c9
