### ISSUE TITLE
Implementar clases pendientes

### ISSUE THREAD

**Issue by CristianDavid** [CristianDavid/field-validator#3]
- NumericColumnInfo.java
- NominalColumnInfo.java
- Normalization.java
- StringDistance.java

**Comment by CristianDavid** [comment]
@oscarAdrianMariscal El profe no ha subido las notas de la clase pasada y no tomé apuntes, no me acuerdo cómo hacer la normalización ni la distancia de cadenas, ¿De casualidad tú tomaste apuntes o algo?

**Comment by oscarAdrianMariscal** [comment]
@CristianDavid recuerdo que el algoritmo para encontrar la distancia de las cadenas se llamaba "levenshtain distance", parece ser popular así que no vas a tener problemas al encontrarlo, y de lo demas no me acuerdo.
